### ISSUE TITLE
Task 7 rejected

### ISSUE THREAD

**Issue by e00dan** [amrosaeed/Nervos-Hackathon#1]
Reason: almost exactly the same as multiple previous submissions.

**Comment by amrosaeed** [comment]
What multiple previous submissions

**Comment by amrosaeed** [comment]
Would you plz elaborate on the rejection reason is it submission
requirements or I just didn't meet the submission deadline

**Comment by e00dan** [comment]
@amrosaeed 

Change your application and smart contracts to be more unique. So far it looks like many other token apps that were submitted. We can't accept the same applications for this challenge, because it looks like clones.
